export default {
  papers: [
    {
      id: 1,
      completed: true,
      subjectSymbol: 'JV31',
      subjectNumber: '01',
      subjectTheme: 'きほん',
      deliveryYear: '2019',
      deliveryMonth: '11',
      deliveryDate: '10',
      subjectTeacher: '山田忠明',
      classSymbol: 'IH13A905',
      attendanceNumber: '15',
      optionClassSymbol: 'IH15A333',
      optionAttendanceNumber: '01',
      studentNumber: '01234',
      myName: '藤原きち',
      homeroomTeacher: '川島ひろ'
    },
    {
      id: 2,
      completed: true,
      subjectSymbol: 'JV31',
      subjectNumber: '01',
      subjectTheme: 'きほん',
      deliveryYear: '2019',
      deliveryMonth: '11',
      deliveryDate: '10',
      subjectTeacher: '山田忠明',
      classSymbol: 'IH13A905',
      attendanceNumber: '15',
      optionClassSymbol: 'IH15A333',
      optionAttendanceNumber: '01',
      studentNumber: '01234',
      myName: '藤原きち',
      homeroomTeacher: '川島ひろ'
    },
    {
      id: 3,
      completed: true,
      subjectSymbol: 'JV31',
      subjectNumber: '01',
      subjectTheme: 'きほん',
      deliveryYear: '2019',
      deliveryMonth: '11',
      deliveryDate: '10',
      subjectTeacher: '山田忠明',
      classSymbol: 'IH13A905',
      attendanceNumber: '15',
      optionClassSymbol: 'IH15A333',
      optionAttendanceNumber: '01',
      studentNumber: '01234',
      myName: '藤原きち',
      homeroomTeacher: '川島ひろ'
    },
    {
      id: 4,
      completed: false,
      subjectSymbol: 'JV31',
      subjectNumber: '01',
      subjectTheme: 'きほん',
      deliveryYear: '2019',
      deliveryMonth: '11',
      deliveryDate: '10',
      subjectTeacher: '山田忠明',
      classSymbol: 'IH13A905',
      attendanceNumber: '15',
      optionClassSymbol: 'IH15A333',
      optionAttendanceNumber: '01',
      studentNumber: '01234',
      myName: '藤原きち',
      homeroomTeacher: '川島ひろ'
    },
    {
      id: 5,
      completed: true,
      subjectSymbol: 'JV31',
      subjectNumber: '01',
      subjectTheme: 'きほん',
      deliveryYear: '2019',
      deliveryMonth: '11',
      deliveryDate: '10',
      subjectTeacher: '山田忠明',
      classSymbol: 'IH13A905',
      attendanceNumber: '15',
      optionClassSymbol: 'IH15A333',
      optionAttendanceNumber: '01',
      studentNumber: '01234',
      myName: '藤原きち',
      homeroomTeacher: '川島ひろ'
    },
    {
      id: 6,
      completed: false,
      subjectSymbol: 'JV31',
      subjectNumber: '01',
      subjectTheme: 'きほん',
      deliveryYear: '2019',
      deliveryMonth: '11',
      deliveryDate: '10',
      subjectTeacher: '山田忠明',
      classSymbol: 'IH13A905',
      attendanceNumber: '15',
      optionClassSymbol: 'IH15A333',
      optionAttendanceNumber: '01',
      studentNumber: '01234',
      myName: '藤原きち',
      homeroomTeacher: '川島ひろ'
    }
  ]
}
